### ISSUE TITLE
Blades in the Dark Sheet Version 3.5 Chrome: Heat / Rep Check boxes not visible

### ISSUE THREAD

**Issue by delwaterman** [joesinghaus/Blades-in-the-Dark#2] opened 2018-05-22 17:06 UTC
Filed here as well: https://github.com/Roll20/roll20-character-sheets/issues/3787
![screen shot 2018-05-22 at 1 03 36 pm](https://user-images.githubusercontent.com/70605/40378227-ebed01cc-5dc0-11e8-8e1c-d0f59ab66a30.png)
<img width="235" alt="screen shot 2018-05-22 at 1 00 53 pm" src="https://user-images.githubusercontent.com/70605/40378230-ee4f8174-5dc0-11e8-8c22-430ffe599834.png">

**Comment by joesinghaus** [comment] 2018-05-22 18:06
Duplicate of #3

**Closed as completed by joesinghaus** 2018-05-22 18:06 UTC
Labels: duplicate
